[코랩(Colab)으로 열기](https://colab.research.google.com/github/dhnam-data/Datafile/blob/main/StatisticsHealthCare/code/13_1_%EC%9D%BC%ED%91%9C%EB%B3%B8_T_%EA%B2%80%EC%A0%95.ipynb)

# 1.일표본 T 검정

귀무가설(H0): 가구의 월평균 민간의료보험료는 29.8 만원이다. [H0: μ1 ＝ 29.8]

대립가설(H1): 가구의 월평균 민간의료보험료는 29.8 만원과 다르다. [H1: μ1 ≠ 29.8]

In [1]:
# 라이브러리 불러오기
import pandas as pd
from scipy import stats
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/1.%ED%8F%89%EA%B7%A0%EB%B9%84%EA%B5%90.xlsx")

df.head()
df.columns


# 'h2005_3aq2(민간의료보험월납입액)'의 결측치 삭제
a = df['h2005_3aq2'].dropna()

# 기술통계
display(a.describe())

# mu0 값 설정
mu = 29.8

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
stats_result = stats.ttest_1samp(a, popmean=mu, alternative='two-sided')
print(stats_result)

count    7300.000000
mean       22.270808
std        28.083217
min         0.000000
25%         0.000000
50%        13.000000
75%        35.000000
max       234.000000
Name: h2005_3aq2, dtype: float64

TtestResult(statistic=np.float64(-22.90672109100743), pvalue=np.float64(3.3454525187706227e-112), df=np.int64(7299))

In [2]:
# 라이브러리 불러오기
import pandas as pd
pd.set_option('display.max_columns', None) # 컬럼 전체보기
!pip install pingouin -q
import pingouin as pg

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/1.%ED%8F%89%EA%B7%A0%EB%B9%84%EA%B5%90.xlsx")

# 'h2005_3aq2(민간의료보험월납입액)'의 결측치 삭제
a = df['h2005_3aq2'].dropna()

# 기술통계
display(a.describe())

# mu0 값 설정
mu = 29.8

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
pg_result = pg.ttest(a, mu, alternative='two-sided')
display(pg_result)

count    7300.000000
mean       22.270808
std        28.083217
min         0.000000
25%         0.000000
50%        13.000000
75%        35.000000
max       234.000000
Name: h2005_3aq2, dtype: float64

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,-22.906721,7299,two-sided,3.345453e-112,"[21.63, 22.92]",0.268103,1.0,1.286e+108

# 2.일표본 T 검정(남성)

귀무가설(H0): 가구주가 남성인 가구의 월평균 민간의료보험료는 29.8 만원이다. [H0: μ1 ＝ 29.8]

대립가설(H1): 가구주가 남성인 가구의 월평균 민간의료보험료는 29.8 만원과 다르다. [H1: μ1 ≠ 29.8]

In [3]:
# 라이브러리 불러오기
import pandas as pd
from scipy import stats
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/1.%ED%8F%89%EA%B7%A0%EB%B9%84%EA%B5%90.xlsx")

# 남자(1) 필터링
df = df[df['h20_g3'] == 1]
# 'h2005_3aq2(민간의료보험월납입액)'의 결측치 삭제
a = df['h2005_3aq2'].dropna()

# 기술통계
display(a.describe())

# mu0 값 설정
mu = 29.8

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
stats_result = stats.ttest_1samp(a, popmean=mu, alternative='two-sided')
print(stats_result)

count    4591.000000
mean       29.233958
std        30.780212
min         0.000000
25%         3.000000
50%        23.000000
75%        45.000000
max       234.000000
Name: h2005_3aq2, dtype: float64

TtestResult(statistic=np.float64(-1.2460368822050396), pvalue=np.float64(0.21281444853718762), df=np.int64(4590))

In [4]:
# 라이브러리 불러오기
import pandas as pd
pd.set_option('display.max_columns', None) # 컬럼 전체보기
!pip install pingouin -q
import pingouin as pg

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/1.%ED%8F%89%EA%B7%A0%EB%B9%84%EA%B5%90.xlsx")

# 남자(1) 필터링
df = df[df['h20_g3'] == 1]
# 'h2005_3aq2(민간의료보험월납입액)'의 결측치 삭제
a = df['h2005_3aq2'].dropna()

# 기술통계
display(a.describe())

# mu0 값 설정
mu = 29.8

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
pg_result = pg.ttest(a, mu, alternative='two-sided')
display(pg_result)

count    4591.000000
mean       29.233958
std        30.780212
min         0.000000
25%         3.000000
50%        23.000000
75%        45.000000
max       234.000000
Name: h2005_3aq2, dtype: float64

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,-1.246037,4590,two-sided,0.212814,"[28.34, 30.12]",0.01839,0.238229,0.036

# 3.일표본 T 검정(여성)

귀무가설(H0): 가구주가 여성인 가구의 월평균 민간의료보험료는 29.8 만원이다. [H0: μ1 ＝ 29.8]

대립가설(H1): 가구주가 여성인 가구의 월평균 민간의료보험료는 29.8 만원과 다르다. [H1: μ1 ≠ 29.8]

In [5]:
# 라이브러리 불러오기
import pandas as pd
from scipy import stats
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/1.%ED%8F%89%EA%B7%A0%EB%B9%84%EA%B5%90.xlsx")

# 여자(2) 필터링
df = df[df['h20_g3'] == 2]
# 'h2005_3aq2(민간의료보험월납입액)'의 결측치 삭제
a = df['h2005_3aq2'].dropna()


# 기술통계
display(a.describe())

# mu0 값 설정
mu = 29.8

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
stats_result = stats.ttest_1samp(a, popmean=mu, alternative='two-sided')
print(stats_result)

count    2709.000000
mean       10.470210
std        17.273334
min         0.000000
25%         0.000000
50%         0.000000
75%        15.000000
max       160.000000
Name: h2005_3aq2, dtype: float64

TtestResult(statistic=np.float64(-58.244573494667875), pvalue=np.float64(0.0), df=np.int64(2708))

In [6]:
# 라이브러리 불러오기
import pandas as pd
pd.set_option('display.max_columns', None) # 컬럼 전체보기
!pip install pingouin -q
import pingouin as pg

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/1.%ED%8F%89%EA%B7%A0%EB%B9%84%EA%B5%90.xlsx")

# 여자(2) 필터링
df = df[df['h20_g3'] == 2]
# 'h2005_3aq2(민간의료보험월납입액)'의 결측치 삭제
a = df['h2005_3aq2'].dropna()

# 기술통계
display(a.describe())

# mu0 값 설정
mu = 29.8

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
pg_result = pg.ttest(a, mu, alternative='two-sided')
display(pg_result)

count    2709.000000
mean       10.470210
std        17.273334
min         0.000000
25%         0.000000
50%         0.000000
75%        15.000000
max       160.000000
Name: h2005_3aq2, dtype: float64

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,-58.244573,2708,two-sided,0.0,"[9.82, 11.12]",1.119054,1.0,inf