[코랩(Colab)으로 열기](https://colab.research.google.com/github/dhnam-data/Datafile/blob/main/StatisticsHealthCare/13_1_%EC%9D%BC%ED%91%9C%EB%B3%B8_T_%EA%B2%80%EC%A0%95.ipynb)

귀무가설(H0): 조사대상자의 혈중 중성지방 수치는 200mg/dL와 같다. [H0: μ1 ＝ 200]

대립가설(H1): 조사대상자의 혈중 중성지방 수치는 200mg/dL와 같지 않다. [H1: μ1 ≠ 200]

In [ ]:
# 라이브러리 불러오기
import pandas as pd
from scipy import stats

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/SampleData%204.xlsx")
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 'HE_TG'의 결측치 삭제
a = df['HE_TG'].dropna()

# 기술통계
display(a.describe())

# mu0 값 설정
mu = 200

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
stats_result = stats.ttest_1samp(a, popmean=mu, alternative='two-sided')
print(stats_result)

shapiro_result = stats.shapiro(a)
print(shapiro_result)

count     670.000000
mean      129.400000
std       100.991148
min        23.000000
25%        67.000000
50%       104.000000
75%       156.000000
max      1269.000000
Name: HE_TG, dtype: float64

TtestResult(statistic=np.float64(-18.095008595755914), pvalue=np.float64(7.146559812362888e-60), df=np.int64(669))
ShapiroResult(statistic=np.float64(0.7154716595753379), pvalue=np.float64(3.471116443106623e-32))

In [ ]:
# 라이브러리 불러오기
import pandas as pd
!pip install pingouin -q
import pingouin as pg

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/SampleData%204.xlsx")
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 'HE_TG'의 결측치 삭제
a = df['HE_TG'].dropna()

# 기술통계
display(a.describe())

# mu0 값 설정
mu = 200

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
pg_result = pg.ttest(a, mu, alternative='two-sided')
display(pg_result)

# Normality Test(정규성 검정)
shapiro_result = pg.normality(a)
display(shapiro_result)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.0/204.0 kB 6.1 MB/s eta 0:00:00

count     670.000000
mean      129.400000
std       100.991148
min        23.000000
25%        67.000000
50%       104.000000
75%       156.000000
max      1269.000000
Name: HE_TG, dtype: float64

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,-18.095009,669,two-sided,7.146560e-60,"[121.74, 137.06]",0.699071,1.0,2.022e+56

              W          pval  normal
HE_TG  0.715472  3.471116e-32   False

귀무가설(H0): 남자의 혈중 중성지방 수치는 200mg/dL와 같다. [H0: μ1 ＝ 200]

대립가설(H1): 남자의 혈중 중성지방 수치는 200mg/dL와 같지 않다. [H1: μ1 ≠ 200]

In [ ]:
# 라이브러리 불러오기
import pandas as pd
from scipy import stats

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/SampleData%204.xlsx")
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 남자(1) 필터링
df = df[df['sex'] == 1]
# 'HE_TG'의 결측치 삭제
a = df['HE_TG'].dropna()


# 기술통계
display(a.describe())

# mu0 값 설정
mu = 200

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
stats_result = stats.ttest_1samp(a, popmean=mu, alternative='two-sided')
print(stats_result)

shapiro_result = stats.shapiro(a)
print(shapiro_result)

count     311.000000
mean      147.163987
std       118.400014
min        23.000000
25%        74.500000
50%       115.000000
75%       184.500000
max      1269.000000
Name: HE_TG, dtype: float64

TtestResult(statistic=np.float64(-7.869705446579628), pvalue=np.float64(5.992913703939238e-14), df=np.int64(310))
ShapiroResult(statistic=np.float64(0.7169322179607374), pvalue=np.float64(1.3067668463720276e-22))

In [ ]:
# 라이브러리 불러오기
import pandas as pd
!pip install pingouin -q
import pingouin as pg

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/SampleData%204.xlsx")
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 남자(1) 필터링
df = df[df['sex'] == 1]
# 'HE_TG'의 결측치 삭제
a = df['HE_TG'].dropna()

# 기술통계
display(a.describe())

# mu0 값 설정
mu = 200

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
pg_result = pg.ttest(a, mu, alternative='two-sided')
display(pg_result)

# Normality Test(정규성 검정)
shapiro_result = pg.normality(a)
display(shapiro_result)

count     311.000000
mean      147.163987
std       118.400014
min        23.000000
25%        74.500000
50%       115.000000
75%       184.500000
max      1269.000000
Name: HE_TG, dtype: float64

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,-7.869705,310,two-sided,5.992914e-14,"[133.95, 160.37]",0.44625,1.0,9.14e+10

              W          pval  normal
HE_TG  0.716932  1.306767e-22   False

귀무가설(H0): 여자의 혈중 중성지방 수치는 200mg/dL와 같다. [H0: μ1 ＝ 200]

대립가설(H1): 여자의 혈중 중성지방 수치는 200mg/dL와 같지 않다. [H1: μ1 ≠ 200]

In [ ]:
# 라이브러리 불러오기
import pandas as pd
from scipy import stats

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/SampleData%204.xlsx")
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 여자(2) 필터링
df = df[df['sex'] == 2]
# 'HE_TG'의 결측치 삭제
a = df['HE_TG'].dropna()


# 기술통계
display(a.describe())

# mu0 값 설정
mu = 200

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
stats_result = stats.ttest_1samp(a, popmean=mu, alternative='two-sided')
print(stats_result)

shapiro_result = stats.shapiro(a)
print(shapiro_result)

count    359.000000
mean     114.011142
std       80.055183
min       28.000000
25%       63.000000
50%       94.000000
75%      138.000000
max      703.000000
Name: HE_TG, dtype: float64

TtestResult(statistic=np.float64(-20.35166532254156), pvalue=np.float64(1.0030610468502746e-61), df=np.int64(358))
ShapiroResult(statistic=np.float64(0.749366854163719), pvalue=np.float64(5.899785088408102e-23))

In [ ]:
# 라이브러리 불러오기
import pandas as pd
!pip install pingouin -q
import pingouin as pg

# 엑셀파일 불러오기 pd.read_excel('파일경로')
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/SampleData%204.xlsx")
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 여자(2) 필터링
df = df[df['sex'] == 2]
# 'HE_TG'의 결측치 삭제
a = df['HE_TG'].dropna()

# 기술통계
display(a.describe())

# mu0 값 설정
mu = 200

# alternative 기본값: 'two-sided', 단측검정: a < mu = 'less', a > mu = 'greater'
pg_result = pg.ttest(a, mu, alternative='two-sided')
display(pg_result)

# Normality Test(정규성 검정)
shapiro_result = pg.normality(a)
display(shapiro_result)

count    359.000000
mean     114.011142
std       80.055183
min       28.000000
25%       63.000000
50%       94.000000
75%      138.000000
max      703.000000
Name: HE_TG, dtype: float64

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,-20.351665,358,two-sided,1.003061e-61,"[105.7, 122.32]",1.07412,1.0,1.519e+58

              W          pval  normal
HE_TG  0.749367  5.899785e-23   False